import Head from "next/head";
import styles from "../styles/Add.module.css";
import EditGoal from "../components/EditGoal";

export default function Goal(props){

    return (
        <div className={styles.container}>
            <Head>
                <title>Add</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div>
                <div className={styles.top}>
                    <div className={styles.heading}><b>{props.default ? 'Add A New Goal':'Edit An Existing Goal'}</b></div>
                    <div className={styles.addSlider}>
                        <div className={styles.card}>
                            <EditGoal goalData={props}/>
                        </div>
                    </div>
                </div>
                <div className={styles.bottom}>
                    <div className={styles.lowerContainer}>
                        <a className={`${styles.bottomBtns} ${styles.btn} ${styles.btn1}`}>Followers</a>
                        <a className={`${styles.bottomBtns} ${styles.btn} ${styles.btn2}`}>Add a note</a>
                    </div>
                </div>
            </div>
        </div>
      )
}

Goal.defaultProps = {
    default: true,
    title: 'Title',
    why: '"Your why"',
    ownNote: 'Add a small note to yourself :)',
    imgSrc: "https://customercare.igloosoftware.com/.api2/api/v1/communities/10068556/previews/thumbnails/4fc20722-5368-e911-80d5-b82a72db46f2?width=680&height=680&crop=False",
};