import Head from 'next/head'
import styles from "../styles/Main.module.css";
import Header from "../components/Header";
import SignedUp from "../components/SignedUp";

import { useContext } from "react";
import AuthContext from "../stores/authContext";

export default function Main() {
  const {user} = useContext(AuthContext);
  console.log(user);

  return (
    <div className={styles.everything}>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {user && (
        <SignedUp />
      )}
    </div>
  )
}
