import Head from 'next/head'
import styles from "../styles/Main.module.css";
import TheMain from '../components/TheMain';

import { useContext } from "react";
import AuthContext from "../stores/authContext";

export default function Main() {
  const {user} = useContext(AuthContext);
  console.log(user);

  return (
    <div className={styles.everything}>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TheMain />
    </div>
  )
}
